sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.3
git:
  depth: 20
branches:
  only:
  - master
before_install:
- gem update --system
- gem install bundler
before_script:
- gem install mdl
- mdl _posts/ *.md --style .mdl.rb
script:
- bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: _site
  verbose: true
  on:
    branch: master
