# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pierre Lavaux
email: pierre@lavaux.lv
description: >
  Notes & Thoughts
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lavaux.lv" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

author: 'Pierre Lavaux'
bio: >
  Cloud Architect and Digital Entrepreneur
author_image: "/assets/images/pierre.jpg"
twitter_username: prlvx
github_username:  PierreLvx

analytics_id: "UA-51062213-9"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

autoprefixer:
  browsers:
  - last 5 versions

gems:
  - jekyll-paginate
  - jekyll-autoprefixer
  - jekyll-feed
