---
# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pierre Lavaux
email: pierre@lavaux.lv
description: >
  A collection of technical notes and thoughts.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://lavaux.lv"  # the base hostname & protocol for your site
paginate: 5  # The number of posts to show per page on your homepage

author: "Pierre Lavaux"
bio: >
  Cloud Architect and Digital Entrepreneur
author_image: "/assets/images/pierre_lavaux.jpg"
github_username: PierreLvx

fb_url: pierre.lvx

analytics_id: "UA-51062213-9"

# SEO Settings

twitter:
  username: prlvx
  card: summary

social:
  name: Pierre Lavaux
  links:
    - https://twitter.com/prlvx
    - https://github.com/PierreLvx
    - https://www.linkedin.com/in/pierrelavaux

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

autoprefixer:
  browsers:
    - last 5 versions

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-autoprefixer
  - jekyll-feed
  - jekyll-sitemap
  - liquid-md5
  - jekyll-seo-tag

# Exclude these files from the build
# https://github.com/jekyll/jekyll/issues/2938#issuecomment-56237068
exclude: ['LICENSE', 'Readme.md', 'Gemfile.lock', 'Gemfile', 'vendor']
